added creating kubearmor spec
Signed-off-by: Rahul Jadhav <nyrahul@gmail.com>

diff --git a/filter-policy b/filter-policy
--- a/filter-policy
+++ b/filter-policy
@@ -4,8 +4,9 @@
 # ./filter-policy -f cilium_policies.yaml -l '^app: checkoutservice' -g checkoutservice.png -o checkoutservice.yaml
 # ./filter-policy -f cilium_policies.yaml -l '^app: .*' -g full.png -o full.yaml
 
+# ./filter-policy -f kubearmor_policies_default_default_server_klshyhrs.yaml -l '^app: cartservice' -g cartservice.png
+
 TMP="/tmp"
-DOT="$TMP/graph.dot"
 
 chk_cmd()
 {
@@ -20,7 +21,10 @@ prerequisites()
 {
 	chk_cmd yq "Download from https://github.com/mikefarah/yq"
 	chk_cmd csplit "Install util csplit"
+	[[ "$GRAPH" != "" ]] && chk_cmd java "java not found"
 	[[ "$GRAPH" != "" ]] && chk_cmd dot "graphviz not found ... use <sudo apt install graphviz>"
+	PUML_JAR=`ls -1 plantuml*.jar`
+	[[ "$GRAPH" != "" ]] && [[ "$PUML_JAR" == "" ]] && echo "need plantuml jar in current folder. Download from https://plantuml.com/download"
 }
 
 usage()
@@ -66,8 +70,9 @@ parse_cmdargs()
 
 split_files()
 {
-	wdir="$TMP/tmp"
+	wdir="$TMP/$USER/tmp"
 	mkdir -p $wdir
+	DOT="$wdir/graph.dot"
 	rm -f $wdir/*
 	csplit -s -z --prefix="$wdir/policy-" --suffix-format="%02d.yaml" $YAML '/---/' '{*}'
 	[[ $? -ne 0 ]] && echo "unable to split policy files" && exit 2
@@ -119,7 +124,7 @@ getEgressRule()
 	echo "$str color=\"$edgecolor\"];" >> $DOT
 }
 
-handle_policy()
+handle_net_policy()
 {
 	[[ "$OUT" != "" ]] && cat $f >> $OUT
 #	cat $f
@@ -154,11 +159,143 @@ filter_net_policy()
 		eps_ns="$ns\n$eps"
 		echo "\"$eps_ns\" [style=\"filled\";fillcolor=\"lightgrey\"]" >> $DOT
 		((matchCnt++))
-		handle_policy $f
+		handle_net_policy $f
 	done
 	echo "processed $c/$totalCnt ... matches $matchCnt       "
 	echo "}" >> $DOT
 	[[ "$GRAPH" != "" ]] && neato -Tpng $DOT -o $GRAPH
+}
+
+# $1 -> indentation point
+# $2 -> multiline input
+add2yaml()
+{
+	while read -r line; do
+		[[ "$line" == "" ]] && continue
+		for((xx=0;xx<$1;xx++)); do
+			echo -en "  " >> $PUML
+		done
+		echo -en "$line\n" >> $PUML
+	done < <(printf '%s\n' "$2")
+}
+
+handle_pathdir()
+{
+	pathdir="path"
+	[[ "$2" == "matchDirectories" ]] && pathdir="dir"
+	echo "processing $1 $2 ..."
+	for((i=0;;i++)); do
+		fromsrc_present=0
+		path=`yq -e eval ".spec.$1.$2[$i].$pathdir" $f 2>/dev/null`
+		[[ $? -ne 0 ]] && break
+		echo "$i. [$path]"
+		for((j=0;;j++)); do
+			fromsrc=`yq -e eval ".spec.$1.$2[$i].fromSource[$j].path" $f 2>/dev/null`
+			[[ $? -ne 0 ]] && break
+			if [ "$fromsrc" != "" ]; then 
+				echo "${psset[$fromsrc]}" | grep "\- $path," >/dev/null
+				if [ $? -ne 0 ]; then
+					psset["$fromsrc"]="- $path,${psset[$fromsrc]}"
+					fromsrc_present=1
+				fi
+			fi
+		done
+		if [ $fromsrc_present -eq 0 ]; then
+			add2yaml 1 "$path:o"
+		fi
+	done
+}
+
+handle_psfile_set()
+{
+	unset psset
+	declare -A psset
+	add2yaml 0 "$1:"
+	handle_pathdir $1 matchPaths
+	handle_pathdir $1 matchDirectories
+	for fromsrc in "${!psset[@]}"; do
+		add2yaml 1 "$fromsrc:"
+		add2yaml 2 "`echo ${psset[$fromsrc]} | tr , '\n'`"
+	done
+}
+
+handle_network_set()
+{
+	add2yaml 0 "network:"
+	for((i=0;;i++)); do
+		fromsrc_present=0
+		prot=`yq -e eval ".spec.network.matchProtocols[$i].protocol" $f 2>/dev/null`
+		[[ $? -ne 0 ]] && break
+		add2yaml 1 "$prot:"
+		for((j=0;;j++)); do
+			fromsrc=`yq -e eval ".spec.network.matchProtocols[$i].fromSource[$j].path" $f 2>/dev/null`
+			[[ $? -ne 0 ]] && break
+			if [ "$fromsrc" != "" ]; then 
+				add2yaml 2 "- $fromsrc"
+				fromsrc_present=1
+			fi
+		done
+		if [ $fromsrc_present -eq 0 ]; then
+			add2yaml 1 "$prot:o"
+		fi
+	done
+}
+
+handle_sys_policy()
+{
+	PUML="policy.puml"
+
+	# policy name
+	name=`yq -e eval '.metadata.name' $f`
+	[[ $? -ne 0 ]] && echo ".metadata.name not found" && return
+	echo -en "@startyaml\nname: $name\n" > $PUML
+
+	# namespace
+	ns=`yq -e eval '.metadata.namespace' $f`
+	[[ $? -ne 0 ]] && ns="default"
+	echo "namespace: $ns" >> $PUML
+
+	# labels
+	lbls=`yq -e eval '.spec.selector.matchLabels' $f`
+	[[ $? -ne 0 ]] && echo "..spec.selector.matchLabels not found" && return
+	echo "labels:" >> $PUML
+	add2yaml 1 "$lbls"
+
+	# process
+	handle_psfile_set "process"
+
+	# file
+	handle_psfile_set "file"
+
+	# network
+	handle_network_set
+
+	echo "@endyaml" >> $PUML
+	cat $PUML
+	java -jar $PUML_JAR $PUML -output "$PWD"
+	[[ "$GRAPH" != "" ]] && mv ${PUML/.puml/.png} $GRAPH
+}
+
+filter_sys_policy()
+{
+	flist=`find $wdir -type f -name "policy-*.yaml"`
+	totalCnt=`echo "$flist" | wc -l`
+	matchCnt=0
+	c=0
+	for f in $flist; do
+#		echo -en "processed $c/$totalCnt ... matches $matchCnt       \r"
+		((c++))
+		kind=`yq eval '.kind' $f`
+		[[ "$kind" != "KubeArmorPolicy" ]] && continue
+		ns=`yq eval '.metadata.namespace' $f`
+		eps=`yq eval '.spec.selector.matchLabels' $f`
+		[[ ! $ns =~ $NS_FILTER ]] && continue
+		[[ ! $eps =~ $LB_FILTER ]] && continue
+		eps_ns="$ns\n$eps"
+		((matchCnt++))
+		handle_sys_policy $f
+	done
+#	echo "processed $c/$totalCnt ... matches $matchCnt       "
 }
 
 main()
@@ -166,6 +303,7 @@ main()
 	prerequisites
 	split_files
 	filter_net_policy
+	filter_sys_policy
 }
 
 parse_cmdargs "$@"
